# Generated by Django 4.2.16 on 2024-09-22 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
    ]
